# Coding Exercises (Part 1)

Now, you will have the opportunity to analyze your own dataset. <br>
__Follow the instructions__ and insert your code! You are either requested to 
- Complete the Code and __Fill in the gaps__. Gaps are marked with "__---__" and are __placeholders__ for your code fragment. 
- Write Code completely __on your own__

In some exercises, you will find questions that can only be answered, if your code is correct and returns the right output! The correct answer is provided below your coding cell. There you can check whether your code is correct.

If you need a hint, check the __Hints Section__ at the end of this Notebook. Exercises and Hints are numerated accordingly.

If you need some further help or if you want to check your code, you can also watch the __solutions videos__ or check the __solutions notebook__.

### Have Fun!

--------------------------------------------------------------------------------------------------------------

## DataFrame Basics III

### Exercise 8: apply(), MultiIndex and Strings

In [1]:
import pandas as pd

In [2]:
cars = pd.read_csv("cars.csv")

In [3]:
cars

,mpg,cylinders,displacement,horsepower,weight,acceleration,model_year,origin,name
0,18.0,8,307.0,130.0,3504,12.0,70,usa,chevrolet chevelle malibu
1,15.0,8,350.0,165.0,3693,11.5,70,usa,buick skylark 320
2,18.0,8,318.0,150.0,3436,11.0,70,usa,plymouth satellite
3,16.0,8,304.0,150.0,3433,12.0,70,usa,amc rebel sst
4,17.0,8,302.0,140.0,3449,10.5,70,usa,ford torino
5,15.0,8,429.0,198.0,4341,10.0,70,usa,ford galaxie 500
6,14.0,8,454.0,220.0,4354,9.0,70,usa,chevrolet impala
7,14.0,8,440.0,215.0,4312,8.5,70,usa,plymouth fury iii
8,14.0,8,455.0,225.0,4425,10.0,70,usa,pontiac catalina
9,15.0,8,390.0,190.0,3850,8.5,70,usa,amc ambassador dpl
10,15.0,8,383.0,170.0,3563,10.0,70,usa,dodge challenger se
11,14.0,8,340.0,160.0,3609,8.0,70,usa,plymouth 'cuda 340
12,15.0,8,400.0,150.0,3761,9.5,70,usa,chevrolet monte carlo
13,14.0,8,455.0,225.0,3086,10.0,70,usa,buick estate wagon (sw)
14,24.0,4,113.0,95.0,2372,15.0,70,japan,toyota corona mark ii
15,22.0,6,198.0,95.0,2833,15.5,70,usa,plymouth duster
16,18.0,6,199.0,97.0,2774,15.5,70,usa,amc hornet
17,21.0,6,200.0,85.0,2587,16.0,70,usa,ford maverick
18,27.0,4,97.0,88.0,2130,14.5,70,japan,datsun pl510
19,26.0,4,97.0,46.0,1835,20.5,70,europe,vw 1131 deluxe sedan
20,25.0,4,110.0,87.0,2672,17.5,70,europe,peugeot 504
21,24.0,4,107.0,90.0,2430,14.5,70,europe,audi 100 ls
22,25.0,4,104.0,95.0,2375,17.5,70,europe,saab 99e
23,26.0,4,121.0,113.0,2234,12.5,70,europe,bmw 2002
24,21.0,6,199.0,90.0,2648,15.0,70,usa,amc gremlin
25,10.0,8,360.0,215.0,4615,14.0,70,usa,ford f250
26,10.0,8,307.0,200.0,4376,15.0,70,usa,chevrolet c20
27,11.0,8,318.0,210.0,4382,13.5,70,usa,dodge d200
28,9.0,8,304.0,193.0,4732,18.5,70,usa,ih 1200d
29,27.0,4,97.0,88.0,2130,14.5,71,japan,datsun pl510
...,...,...,...,...,...,...,...,...,...
368,27.0,4,112.0,88.0,2640,18.6,82,usa,chevrolet cavalier wagon
369,34.0,4,112.0,88.0,2395,18.0,82,usa,chevrolet cavalier 2-door
370,31.0,4,112.0,85.0,2575,16.2,82,usa,pontiac j2000 se hatchback
371,29.0,4,135.0,84.0,2525,16.0,82,usa,dodge aries se
372,27.0,4,151.0,90.0,2735,18.0,82,usa,pontiac phoenix
373,24.0,4,140.0,92.0,2865,16.4,82,usa,ford fairmont futura
374,23.0,4,151.0,NaN,3035,20.5,82,usa,amc concord dl
375,36.0,4,105.0,74.0,1980,15.3,82,europe,vw rabbit l
376,37.0,4,91.0,68.0,2025,18.2,82,japan,mazda glc custom l
377,31.0,4,91.0,68.0,1970,17.6,82,japan,mazda glc custom
378,38.0,4,105.0,63.0,2125,14.7,82,usa,plymouth horizon miser
379,36.0,4,98.0,70.0,2125,17.3,82,usa,mercury lynx l
380,36.0,4,120.0,88.0,2160,14.5,82,japan,nissan stanza xe
381,36.0,4,107.0,75.0,2205,14.5,82,japan,honda accord
382,34.0,4,108.0,70.0,2245,16.9,82,japan,toyota corolla
383,38.0,4,91.0,67.0,1965,15.0,82,japan,honda civic
384,32.0,4,91.0,67.0,1965,15.7,82,japan,honda civic (auto)
385,38.0,4,91.0,67.0,1995,16.2,82,japan,datsun 310 gx
386,25.0,6,181.0,110.0,2945,16.4,82,usa,buick century limited
387,38.0,6,262.0,85.0,3015,17.0,82,usa,oldsmobile cutlass ciera (diesel)
388,26.0,4,156.0,92.0,2585,14.5,82,usa,chrysler lebaron medallion
389,22.0,6,232.0,112.0,2835,14.7,82,usa,ford granada l
390,32.0,4,144.0,96.0,2665,13.9,82,japan,toyota celica gt
391,36.0,4,135.0,84.0,2370,13.0,82,usa,dodge charger 2.2
392,27.0,4,151.0,90.0,2950,17.3,82,usa,chevrolet camaro
393,27.0,4,140.0,86.0,2790,15.6,82,usa,ford mustang gl
394,44.0,4,97.0,52.0,2130,24.6,82,europe,vw pickup
395,32.0,4,135.0,84.0,2295,11.6,82,usa,dodge rampage
396,28.0,4,120.0,79.0,2625,18.6,82,usa,ford ranger
397,31.0,4,119.0,82.0,2720,19.4,82,usa,chevrolet s-10

61. __Calculate__ for all __numerical columns__ the __range between highest and lowest__ value! __Fill in the gaps!__ The range for __mpg__ is...?

In [4]:
cars.iloc[:, :-2].apply(lambda x: x.max() - x.min(), axis = 0)

mpg               37.6
cylinders          5.0
displacement     387.0
horsepower       184.0
weight          3527.0
acceleration      16.8
model_year        12.0
dtype: float64

The range for mpg is ... 37.6!

62. Create a __MultiIndex__ for the __cars__ DataFrame with the columns __"model_year"__ (outer level) and __"origin"__ (inner level). __Save__ the change!

In [4]:
cars.set_index(["model_year", "origin"], inplace = True)

63. __Sort__ both index levels in __ascending__ order! __Save__ the change!

In [5]:
cars.sort_index(ascending = True, inplace = True )

__Inspect__ Cars! What is the __name__ of the __second__ car?

In [6]:
cars

                    mpg  cylinders  displacement  horsepower  weight  \
model_year origin
70         europe  26.0          4          97.0        46.0    1835
           europe  25.0          4         110.0        87.0    2672
           europe  24.0          4         107.0        90.0    2430
           europe  25.0          4         104.0        95.0    2375
           europe  26.0          4         121.0       113.0    2234
           japan   24.0          4         113.0        95.0    2372
           japan   27.0          4          97.0        88.0    2130
           usa     18.0          8         307.0       130.0    3504
           usa     15.0          8         350.0       165.0    3693
           usa     18.0          8         318.0       150.0    3436
           usa     16.0          8         304.0       150.0    3433
           usa     17.0          8         302.0       140.0    3449
           usa     15.0          8         429.0       198.0    4341
           usa     14.0          8         454.0       220.0    4354
           usa     14.0          8         440.0       215.0    4312
           usa     14.0          8         455.0       225.0    4425
           usa     15.0          8         390.0       190.0    3850
           usa     15.0          8         383.0       170.0    3563
           usa     14.0          8         340.0       160.0    3609
           usa     15.0          8         400.0       150.0    3761
           usa     14.0          8         455.0       225.0    3086
           usa     22.0          6         198.0        95.0    2833
           usa     18.0          6         199.0        97.0    2774
           usa     21.0          6         200.0        85.0    2587
           usa     21.0          6         199.0        90.0    2648
           usa     10.0          8         360.0       215.0    4615
           usa     10.0          8         307.0       200.0    4376
           usa     11.0          8         318.0       210.0    4382
           usa      9.0          8         304.0       193.0    4732
71         europe  28.0          4         116.0        90.0    2123
...                 ...        ...           ...         ...     ...
82         europe  44.0          4          97.0        52.0    2130
           japan   37.0          4          91.0        68.0    2025
           japan   31.0          4          91.0        68.0    1970
           japan   36.0          4         120.0        88.0    2160
           japan   36.0          4         107.0        75.0    2205
           japan   34.0          4         108.0        70.0    2245
           japan   38.0          4          91.0        67.0    1965
           japan   32.0          4          91.0        67.0    1965
           japan   38.0          4          91.0        67.0    1995
           japan   32.0          4         144.0        96.0    2665
           usa     28.0          4         112.0        88.0    2605
           usa     27.0          4         112.0        88.0    2640
           usa     34.0          4         112.0        88.0    2395
           usa     31.0          4         112.0        85.0    2575
           usa     29.0          4         135.0        84.0    2525
           usa     27.0          4         151.0        90.0    2735
           usa     24.0          4         140.0        92.0    2865
           usa     23.0          4         151.0         NaN    3035
           usa     38.0          4         105.0        63.0    2125
           usa     36.0          4          98.0        70.0    2125
           usa     25.0          6         181.0       110.0    2945
           usa     38.0          6         262.0        85.0    3015
           usa     26.0          4         156.0        92.0    2585
           usa     22.0          6         232.0       112.0    2835
           usa     36.0          4         135.0        84.0    2370
           usa     27.0          4         151.0        90.0    2950
           usa     27.0          4         140.0        86.0    2790
           usa     32.0          4         135.0        84.0    2295
           usa     28.0          4         120.0        79.0    2625
           usa     31.0          4         119.0        82.0    2720

                   acceleration                               name
model_year origin
70         europe          20.5               vw 1131 deluxe sedan
           europe          17.5                        peugeot 504
           europe          14.5                        audi 100 ls
           europe          17.5                           saab 99e
           europe          12.5                           bmw 2002
           japan           15.0              toyota corona mark ii
           japan           14.5                       datsun pl510
           usa             12.0          chevrolet chevelle malibu
           usa             11.5                  buick skylark 320
           usa             11.0                 plymouth satellite
           usa             12.0                      amc rebel sst
           usa             10.5                        ford torino
           usa             10.0                   ford galaxie 500
           usa              9.0                   chevrolet impala
           usa              8.5                  plymouth fury iii
           usa             10.0                   pontiac catalina
           usa              8.5                 amc ambassador dpl
           usa             10.0                dodge challenger se
           usa              8.0                 plymouth 'cuda 340
           usa              9.5              chevrolet monte carlo
           usa             10.0            buick estate wagon (sw)
           usa             15.5                    plymouth duster
           usa             15.5                         amc hornet
           usa             16.0                      ford maverick
           usa             15.0                        amc gremlin
           usa             14.0                          ford f250
           usa             15.0                      chevrolet c20
           usa             13.5                         dodge d200
           usa             18.5                           ih 1200d
71         europe          14.0                          opel 1900
...                         ...                                ...
82         europe          24.6                          vw pickup
           japan           18.2                 mazda glc custom l
           japan           17.6                   mazda glc custom
           japan           14.5                   nissan stanza xe
           japan           14.5                       honda accord
           japan           16.9                     toyota corolla
           japan           15.0                        honda civic
           japan           15.7                 honda civic (auto)
           japan           16.2                      datsun 310 gx
           japan           13.9                   toyota celica gt
           usa             19.6                 chevrolet cavalier
           usa             18.6           chevrolet cavalier wagon
           usa             18.0          chevrolet cavalier 2-door
           usa             16.2         pontiac j2000 se hatchback
           usa             16.0                     dodge aries se
           usa             18.0                    pontiac phoenix
           usa             16.4               ford fairmont futura
           usa             20.5                     amc concord dl
           usa             14.7             plymouth horizon miser
           usa             17.3                     mercury lynx l
           usa             16.4              buick century limited
           usa             17.0  oldsmobile cutlass ciera (diesel)
           usa             14.5         chrysler lebaron medallion
           usa             14.7                     ford granada l
           usa             13.0                  dodge charger 2.2
           usa             17.3                   chevrolet camaro
           usa             15.6                    ford mustang gl
           usa             11.6                      dodge rampage
           usa             18.6                        ford ranger
           usa             19.4                     chevrolet s-10

[398 rows x 7 columns]

The name of the second car is ... peugeot 504!

64. __Select__ all cars with the "model_year" __75__!

In [7]:
cars.loc[75]

,mpg,cylinders,displacement,horsepower,weight,acceleration,name
origin,,,,,,,
europe,25.0,4,90.0,71.0,2223,16.5,vw dasher
europe,29.0,4,90.0,70.0,1937,14.0,vw rabbit
europe,23.0,4,115.0,95.0,2694,15.0,audi 100ls
europe,23.0,4,120.0,88.0,2957,17.0,peugeot 504
europe,22.0,4,121.0,98.0,2945,14.5,volvo 244dl
europe,25.0,4,121.0,115.0,2671,13.5,saab 99le
japan,29.0,4,97.0,75.0,2171,16.0,toyota corolla
japan,24.0,4,134.0,96.0,2702,13.5,toyota corona
japan,24.0,4,119.0,97.0,2545,17.0,datsun 710
japan,33.0,4,91.0,53.0,1795,17.5,honda civic cvcc
usa,19.0,6,225.0,95.0,3264,16.0,plymouth valiant custom
usa,18.0,6,250.0,105.0,3459,16.0,chevrolet nova
usa,15.0,6,250.0,72.0,3432,21.0,mercury monarch
usa,15.0,6,250.0,72.0,3158,19.5,ford maverick
usa,16.0,8,400.0,170.0,4668,11.5,pontiac catalina
usa,15.0,8,350.0,145.0,4440,14.0,chevrolet bel air
usa,16.0,8,318.0,150.0,4498,14.5,plymouth grand fury
usa,14.0,8,351.0,148.0,4657,13.5,ford ltd
usa,17.0,6,231.0,110.0,3907,21.0,buick century
usa,16.0,6,250.0,105.0,3897,18.5,chevrolet chevelle malibu
usa,15.0,6,258.0,110.0,3730,19.0,amc matador
usa,18.0,6,225.0,95.0,3785,19.0,plymouth fury
usa,21.0,6,231.0,110.0,3039,15.0,buick skyhawk
usa,20.0,8,262.0,110.0,3221,13.5,chevrolet monza 2+2
usa,13.0,8,302.0,129.0,3169,12.0,ford mustang ii
usa,23.0,4,140.0,83.0,2639,17.0,ford pinto
usa,20.0,6,232.0,100.0,2914,16.0,amc gremlin
usa,23.0,4,140.0,78.0,2592,18.5,pontiac astro
usa,18.0,6,171.0,97.0,2984,14.5,ford pinto
usa,19.0,6,232.0,90.0,3211,17.0,amc pacer

65. __Select__ all cars with the "model_year" __76__ from __japan__! __How many__ cars do we get?

In [8]:
cars.loc[(76, "japan")]

                    mpg  cylinders  displacement  horsepower  weight  \
model_year origin
76         japan   33.0          4          91.0        53.0    1795
           japan   32.0          4          85.0        70.0    1990
           japan   28.0          4          97.0        75.0    2155
           japan   19.0          6         156.0       108.0    2930

                   acceleration            name
model_year origin
76         japan           17.4     honda civic
           japan           17.0    datsun b-210
           japan           16.4  toyota corolla
           japan           15.5  toyota mark ii

There are ... 4 cars!

66. __Select__ all cars with the "model_year" __77__ and __79__  from __japan__! And only the columns __"mpg"__ and __"name"__! What is the __mpg__ of __datsun 210__?

In [9]:
cars.loc[([77,79], "japan"), ["mpg", "name"]]

                    mpg                     name
model_year origin
77         japan   31.5        honda accord cvcc
           japan   33.5    datsun f-10 hatchback
           japan   26.0  toyota corolla liftback
           japan   30.0                subaru dl
           japan   22.0               datsun 810
           japan   21.5               mazda rx-4
79         japan   34.1         mazda glc deluxe
           japan   31.8               datsun 210

The mpg of datsun 210 is ... 31.8!

67. __Swap the levels__ of the MultiIndex and then __sort__ the new MultiIndex in __ascending__ order! __Reassign cars__! __Fill in the gaps__!

In [10]:
cars = cars.swaplevel().sort_index(ascending = True)

In [11]:
cars

                    mpg  cylinders  displacement  horsepower  weight  \
origin model_year
europe 70          26.0          4          97.0        46.0    1835
       70          25.0          4         110.0        87.0    2672
       70          24.0          4         107.0        90.0    2430
       70          25.0          4         104.0        95.0    2375
       70          26.0          4         121.0       113.0    2234
       71          28.0          4         116.0        90.0    2123
       71          30.0          4          79.0        70.0    2074
       71          30.0          4          88.0        76.0    2065
       71          27.0          4          97.0        60.0    1834
       72          23.0          4          97.0        54.0    2254
       72          18.0          4         121.0       112.0    2933
       72          22.0          4         121.0        76.0    2511
       72          21.0          4         120.0        87.0    2979
       72          26.0          4          96.0        69.0    2189
       73          26.0          4          97.0        46.0    1950
       73          26.0          4          98.0        90.0    2265
       73          29.0          4          68.0        49.0    1867
       73          24.0          4         116.0        75.0    2158
       73          20.0          4         114.0        91.0    2582
       73          19.0          4         121.0       112.0    2868
       73          24.0          4         121.0       110.0    2660
       74          29.0          4          98.0        83.0    2219
       74          26.0          4          79.0        67.0    1963
       74          26.0          4          97.0        78.0    2300
       74          24.0          4          90.0        75.0    2108
       74          26.0          4         116.0        75.0    2246
       74          31.0          4          79.0        67.0    2000
       75          25.0          4          90.0        71.0    2223
       75          29.0          4          90.0        70.0    1937
       75          23.0          4         115.0        95.0    2694
...                 ...        ...           ...         ...     ...
usa    81          23.5          6         173.0       110.0    2725
       81          30.0          4         135.0        84.0    2385
       81          39.0          4          86.0        64.0    1875
       81          34.7          4         105.0        63.0    2215
       81          34.4          4          98.0        65.0    2045
       81          29.9          4          98.0        65.0    2380
       81          22.4          6         231.0       110.0    3415
       81          26.6          8         350.0       105.0    3725
       81          20.2          6         200.0        88.0    3060
       81          17.6          6         225.0        85.0    3465
       82          28.0          4         112.0        88.0    2605
       82          27.0          4         112.0        88.0    2640
       82          34.0          4         112.0        88.0    2395
       82          31.0          4         112.0        85.0    2575
       82          29.0          4         135.0        84.0    2525
       82          27.0          4         151.0        90.0    2735
       82          24.0          4         140.0        92.0    2865
       82          23.0          4         151.0         NaN    3035
       82          38.0          4         105.0        63.0    2125
       82          36.0          4          98.0        70.0    2125
       82          25.0          6         181.0       110.0    2945
       82          38.0          6         262.0        85.0    3015
       82          26.0          4         156.0        92.0    2585
       82          22.0          6         232.0       112.0    2835
       82          36.0          4         135.0        84.0    2370
       82          27.0          4         151.0        90.0    2950
       82          27.0          4         140.0        86.0    2790
       82          32.0          4         135.0        84.0    2295
       82          28.0          4         120.0        79.0    2625
       82          31.0          4         119.0        82.0    2720

                   acceleration                               name
origin model_year
europe 70                  20.5               vw 1131 deluxe sedan
       70                  17.5                        peugeot 504
       70                  14.5                        audi 100 ls
       70                  17.5                           saab 99e
       70                  12.5                           bmw 2002
       71                  14.0                          opel 1900
       71                  19.5                        peugeot 304
       71                  14.5                          fiat 124b
       71                  19.0                       vw model 111
       72                  23.5                          vw type 3
       72                  14.5                    volvo 145e (sw)
       72                  18.0                        vw 411 (sw)
       72                  19.5                   peugeot 504 (sw)
       72                  18.0                    renault 12 (sw)
       73                  21.0                    vw super beetle
       73                  15.5               fiat 124 sport coupe
       73                  19.5                           fiat 128
       73                  15.5                         opel manta
       73                  14.0                         audi 100ls
       73                  15.5                        volvo 144ea
       73                  14.0                          saab 99le
       74                  16.5                           audi fox
       74                  15.5                          vw dasher
       74                  14.5                         opel manta
       74                  15.5                           fiat 128
       74                  14.0                        fiat 124 tc
       74                  16.0                          fiat x1.9
       75                  16.5                          vw dasher
       75                  14.0                          vw rabbit
       75                  15.0                         audi 100ls
...                         ...                                ...
usa    81                  12.6                 chevrolet citation
       81                  12.9                   plymouth reliant
       81                  16.4                     plymouth champ
       81                  14.9                 plymouth horizon 4
       81                  16.2                     ford escort 4w
       81                  20.7                     ford escort 2h
       81                  15.8                      buick century
       81                  19.0              oldsmobile cutlass ls
       81                  17.1                    ford granada gl
       81                  16.6             chrysler lebaron salon
       82                  19.6                 chevrolet cavalier
       82                  18.6           chevrolet cavalier wagon
       82                  18.0          chevrolet cavalier 2-door
       82                  16.2         pontiac j2000 se hatchback
       82                  16.0                     dodge aries se
       82                  18.0                    pontiac phoenix
       82                  16.4               ford fairmont futura
       82                  20.5                     amc concord dl
       82                  14.7             plymouth horizon miser
       82                  17.3                     mercury lynx l
       82                  16.4              buick century limited
       82                  17.0  oldsmobile cutlass ciera (diesel)
       82                  14.5         chrysler lebaron medallion
       82                  14.7                     ford granada l
       82                  13.0                  dodge charger 2.2
       82                  17.3                   chevrolet camaro
       82                  15.6                    ford mustang gl
       82                  11.6                      dodge rampage
       82                  18.6                        ford ranger
       82                  19.4                     chevrolet s-10

[398 rows x 7 columns]

68. __Reset__ the __index__ of __cars__ and create a RangeIndex! __Save__ the change!

In [12]:
cars.reset_index(inplace = True)

In [13]:
cars

,origin,model_year,mpg,cylinders,displacement,horsepower,weight,acceleration,name
0,europe,70,26.0,4,97.0,46.0,1835,20.5,vw 1131 deluxe sedan
1,europe,70,25.0,4,110.0,87.0,2672,17.5,peugeot 504
2,europe,70,24.0,4,107.0,90.0,2430,14.5,audi 100 ls
3,europe,70,25.0,4,104.0,95.0,2375,17.5,saab 99e
4,europe,70,26.0,4,121.0,113.0,2234,12.5,bmw 2002
5,europe,71,28.0,4,116.0,90.0,2123,14.0,opel 1900
6,europe,71,30.0,4,79.0,70.0,2074,19.5,peugeot 304
7,europe,71,30.0,4,88.0,76.0,2065,14.5,fiat 124b
8,europe,71,27.0,4,97.0,60.0,1834,19.0,vw model 111
9,europe,72,23.0,4,97.0,54.0,2254,23.5,vw type 3
10,europe,72,18.0,4,121.0,112.0,2933,14.5,volvo 145e (sw)
11,europe,72,22.0,4,121.0,76.0,2511,18.0,vw 411 (sw)
12,europe,72,21.0,4,120.0,87.0,2979,19.5,peugeot 504 (sw)
13,europe,72,26.0,4,96.0,69.0,2189,18.0,renault 12 (sw)
14,europe,73,26.0,4,97.0,46.0,1950,21.0,vw super beetle
15,europe,73,26.0,4,98.0,90.0,2265,15.5,fiat 124 sport coupe
16,europe,73,29.0,4,68.0,49.0,1867,19.5,fiat 128
17,europe,73,24.0,4,116.0,75.0,2158,15.5,opel manta
18,europe,73,20.0,4,114.0,91.0,2582,14.0,audi 100ls
19,europe,73,19.0,4,121.0,112.0,2868,15.5,volvo 144ea
20,europe,73,24.0,4,121.0,110.0,2660,14.0,saab 99le
21,europe,74,29.0,4,98.0,83.0,2219,16.5,audi fox
22,europe,74,26.0,4,79.0,67.0,1963,15.5,vw dasher
23,europe,74,26.0,4,97.0,78.0,2300,14.5,opel manta
24,europe,74,24.0,4,90.0,75.0,2108,15.5,fiat 128
25,europe,74,26.0,4,116.0,75.0,2246,14.0,fiat 124 tc
26,europe,74,31.0,4,79.0,67.0,2000,16.0,fiat x1.9
27,europe,75,25.0,4,90.0,71.0,2223,16.5,vw dasher
28,europe,75,29.0,4,90.0,70.0,1937,14.0,vw rabbit
29,europe,75,23.0,4,115.0,95.0,2694,15.0,audi 100ls
...,...,...,...,...,...,...,...,...,...
368,usa,81,23.5,6,173.0,110.0,2725,12.6,chevrolet citation
369,usa,81,30.0,4,135.0,84.0,2385,12.9,plymouth reliant
370,usa,81,39.0,4,86.0,64.0,1875,16.4,plymouth champ
371,usa,81,34.7,4,105.0,63.0,2215,14.9,plymouth horizon 4
372,usa,81,34.4,4,98.0,65.0,2045,16.2,ford escort 4w
373,usa,81,29.9,4,98.0,65.0,2380,20.7,ford escort 2h
374,usa,81,22.4,6,231.0,110.0,3415,15.8,buick century
375,usa,81,26.6,8,350.0,105.0,3725,19.0,oldsmobile cutlass ls
376,usa,81,20.2,6,200.0,88.0,3060,17.1,ford granada gl
377,usa,81,17.6,6,225.0,85.0,3465,16.6,chrysler lebaron salon
378,usa,82,28.0,4,112.0,88.0,2605,19.6,chevrolet cavalier
379,usa,82,27.0,4,112.0,88.0,2640,18.6,chevrolet cavalier wagon
380,usa,82,34.0,4,112.0,88.0,2395,18.0,chevrolet cavalier 2-door
381,usa,82,31.0,4,112.0,85.0,2575,16.2,pontiac j2000 se hatchback
382,usa,82,29.0,4,135.0,84.0,2525,16.0,dodge aries se
383,usa,82,27.0,4,151.0,90.0,2735,18.0,pontiac phoenix
384,usa,82,24.0,4,140.0,92.0,2865,16.4,ford fairmont futura
385,usa,82,23.0,4,151.0,NaN,3035,20.5,amc concord dl
386,usa,82,38.0,4,105.0,63.0,2125,14.7,plymouth horizon miser
387,usa,82,36.0,4,98.0,70.0,2125,17.3,mercury lynx l
388,usa,82,25.0,6,181.0,110.0,2945,16.4,buick century limited
389,usa,82,38.0,6,262.0,85.0,3015,17.0,oldsmobile cutlass ciera (diesel)
390,usa,82,26.0,4,156.0,92.0,2585,14.5,chrysler lebaron medallion
391,usa,82,22.0,6,232.0,112.0,2835,14.7,ford granada l
392,usa,82,36.0,4,135.0,84.0,2370,13.0,dodge charger 2.2
393,usa,82,27.0,4,151.0,90.0,2950,17.3,chevrolet camaro
394,usa,82,27.0,4,140.0,86.0,2790,15.6,ford mustang gl
395,usa,82,32.0,4,135.0,84.0,2295,11.6,dodge rampage
396,usa,82,28.0,4,120.0,79.0,2625,18.6,ford ranger
397,usa,82,31.0,4,119.0,82.0,2720,19.4,chevrolet s-10

69. __Convert__ all elements in the __origin__ column to __titlecase__! __Overwrite__ the __origin__ column!

In [14]:
cars.origin = cars.origin.str.title()

In [15]:
cars

,origin,model_year,mpg,cylinders,displacement,horsepower,weight,acceleration,name
0,Europe,70,26.0,4,97.0,46.0,1835,20.5,vw 1131 deluxe sedan
1,Europe,70,25.0,4,110.0,87.0,2672,17.5,peugeot 504
2,Europe,70,24.0,4,107.0,90.0,2430,14.5,audi 100 ls
3,Europe,70,25.0,4,104.0,95.0,2375,17.5,saab 99e
4,Europe,70,26.0,4,121.0,113.0,2234,12.5,bmw 2002
5,Europe,71,28.0,4,116.0,90.0,2123,14.0,opel 1900
6,Europe,71,30.0,4,79.0,70.0,2074,19.5,peugeot 304
7,Europe,71,30.0,4,88.0,76.0,2065,14.5,fiat 124b
8,Europe,71,27.0,4,97.0,60.0,1834,19.0,vw model 111
9,Europe,72,23.0,4,97.0,54.0,2254,23.5,vw type 3
10,Europe,72,18.0,4,121.0,112.0,2933,14.5,volvo 145e (sw)
11,Europe,72,22.0,4,121.0,76.0,2511,18.0,vw 411 (sw)
12,Europe,72,21.0,4,120.0,87.0,2979,19.5,peugeot 504 (sw)
13,Europe,72,26.0,4,96.0,69.0,2189,18.0,renault 12 (sw)
14,Europe,73,26.0,4,97.0,46.0,1950,21.0,vw super beetle
15,Europe,73,26.0,4,98.0,90.0,2265,15.5,fiat 124 sport coupe
16,Europe,73,29.0,4,68.0,49.0,1867,19.5,fiat 128
17,Europe,73,24.0,4,116.0,75.0,2158,15.5,opel manta
18,Europe,73,20.0,4,114.0,91.0,2582,14.0,audi 100ls
19,Europe,73,19.0,4,121.0,112.0,2868,15.5,volvo 144ea
20,Europe,73,24.0,4,121.0,110.0,2660,14.0,saab 99le
21,Europe,74,29.0,4,98.0,83.0,2219,16.5,audi fox
22,Europe,74,26.0,4,79.0,67.0,1963,15.5,vw dasher
23,Europe,74,26.0,4,97.0,78.0,2300,14.5,opel manta
24,Europe,74,24.0,4,90.0,75.0,2108,15.5,fiat 128
25,Europe,74,26.0,4,116.0,75.0,2246,14.0,fiat 124 tc
26,Europe,74,31.0,4,79.0,67.0,2000,16.0,fiat x1.9
27,Europe,75,25.0,4,90.0,71.0,2223,16.5,vw dasher
28,Europe,75,29.0,4,90.0,70.0,1937,14.0,vw rabbit
29,Europe,75,23.0,4,115.0,95.0,2694,15.0,audi 100ls
...,...,...,...,...,...,...,...,...,...
368,Usa,81,23.5,6,173.0,110.0,2725,12.6,chevrolet citation
369,Usa,81,30.0,4,135.0,84.0,2385,12.9,plymouth reliant
370,Usa,81,39.0,4,86.0,64.0,1875,16.4,plymouth champ
371,Usa,81,34.7,4,105.0,63.0,2215,14.9,plymouth horizon 4
372,Usa,81,34.4,4,98.0,65.0,2045,16.2,ford escort 4w
373,Usa,81,29.9,4,98.0,65.0,2380,20.7,ford escort 2h
374,Usa,81,22.4,6,231.0,110.0,3415,15.8,buick century
375,Usa,81,26.6,8,350.0,105.0,3725,19.0,oldsmobile cutlass ls
376,Usa,81,20.2,6,200.0,88.0,3060,17.1,ford granada gl
377,Usa,81,17.6,6,225.0,85.0,3465,16.6,chrysler lebaron salon
378,Usa,82,28.0,4,112.0,88.0,2605,19.6,chevrolet cavalier
379,Usa,82,27.0,4,112.0,88.0,2640,18.6,chevrolet cavalier wagon
380,Usa,82,34.0,4,112.0,88.0,2395,18.0,chevrolet cavalier 2-door
381,Usa,82,31.0,4,112.0,85.0,2575,16.2,pontiac j2000 se hatchback
382,Usa,82,29.0,4,135.0,84.0,2525,16.0,dodge aries se
383,Usa,82,27.0,4,151.0,90.0,2735,18.0,pontiac phoenix
384,Usa,82,24.0,4,140.0,92.0,2865,16.4,ford fairmont futura
385,Usa,82,23.0,4,151.0,NaN,3035,20.5,amc concord dl
386,Usa,82,38.0,4,105.0,63.0,2125,14.7,plymouth horizon miser
387,Usa,82,36.0,4,98.0,70.0,2125,17.3,mercury lynx l
388,Usa,82,25.0,6,181.0,110.0,2945,16.4,buick century limited
389,Usa,82,38.0,6,262.0,85.0,3015,17.0,oldsmobile cutlass ciera (diesel)
390,Usa,82,26.0,4,156.0,92.0,2585,14.5,chrysler lebaron medallion
391,Usa,82,22.0,6,232.0,112.0,2835,14.7,ford granada l
392,Usa,82,36.0,4,135.0,84.0,2370,13.0,dodge charger 2.2
393,Usa,82,27.0,4,151.0,90.0,2950,17.3,chevrolet camaro
394,Usa,82,27.0,4,140.0,86.0,2790,15.6,ford mustang gl
395,Usa,82,32.0,4,135.0,84.0,2295,11.6,dodge rampage
396,Usa,82,28.0,4,120.0,79.0,2625,18.6,ford ranger
397,Usa,82,31.0,4,119.0,82.0,2720,19.4,chevrolet s-10

Now, we want to __extract the manufacturer names__ from the column __"name"__. <br>
70. __Split__ the strings in the column __"name"__ on the very __first whitespace__ and __expand__ the splitted strings into __separate columns__! __Save__ new DataFrame in the variable __split__! __Fill in the gaps!__

In [16]:
split = cars.name.str.split(pat = " ", n = 1, expand = True)

__Inspect__!

In [17]:
split

              0                       1
0            vw       1131 deluxe sedan
1       peugeot                     504
2          audi                  100 ls
3          saab                     99e
4           bmw                    2002
5          opel                    1900
6       peugeot                     304
7          fiat                    124b
8            vw               model 111
9            vw                  type 3
10        volvo               145e (sw)
11           vw                411 (sw)
12      peugeot                504 (sw)
13      renault                 12 (sw)
14           vw            super beetle
15         fiat         124 sport coupe
16         fiat                     128
17         opel                   manta
18         audi                   100ls
19        volvo                   144ea
20         saab                    99le
21         audi                     fox
22           vw                  dasher
23         opel                   manta
24         fiat                     128
25         fiat                  124 tc
26         fiat                    x1.9
27           vw                  dasher
28           vw                  rabbit
29         audi                   100ls
..          ...                     ...
368   chevrolet                citation
369    plymouth                 reliant
370    plymouth                   champ
371    plymouth               horizon 4
372        ford               escort 4w
373        ford               escort 2h
374       buick                 century
375  oldsmobile              cutlass ls
376        ford              granada gl
377    chrysler           lebaron salon
378   chevrolet                cavalier
379   chevrolet          cavalier wagon
380   chevrolet         cavalier 2-door
381     pontiac      j2000 se hatchback
382       dodge                aries se
383     pontiac                 phoenix
384        ford         fairmont futura
385         amc              concord dl
386    plymouth           horizon miser
387     mercury                  lynx l
388       buick         century limited
389  oldsmobile  cutlass ciera (diesel)
390    chrysler       lebaron medallion
391        ford               granada l
392       dodge             charger 2.2
393   chevrolet                  camaro
394        ford              mustang gl
395       dodge                 rampage
396        ford                  ranger
397   chevrolet                    s-10

[398 rows x 2 columns]

71. __Select__ the __first column__ and determine the __frequency of unique values__. __Fill in the gaps__! Which manufacturer is __most frequent__?

In [19]:
split[0].value_counts()

ford             51
chevrolet        47
plymouth         31
dodge            28
amc              28
toyota           26
datsun           23
vw               22
buick            17
pontiac          16
honda            13
mazda            12
mercury          12
oldsmobile       10
fiat              8
peugeot           8
audi              7
chrysler          6
volvo             6
renault           5
saab              4
subaru            4
opel              4
mercedes-benz     3
cadillac          2
bmw               2
ih                1
triumph           1
nissan            1
Name: 0, dtype: int64

There are 51 cars from the manufacturer ... Ford!

72. Let´s __doublecheck__ the result from above. Check __how many__ car names in the column "names" __contain "ford"__!

In [20]:
cars.name.str.contains("ford").sum()

51

It´s ... again 51! It seems that the very first word in the column "name" is always the manufacturer name.

# Well Done!

------------------------------

# Hints (Spoiler!)

61. apply() method, maximum - minimum

62. set_index() method, pass list with column labels

63. sort_index() method

64. pass outer index labels to loc operator

65. cars.loc[(outer index labels, inner index labels)]

66. cars.loc[(outer index labels, inner index labels), column labels]

67. methods swaplevel() and sort_index()

68. reset_index() method

69. string(str)-method title()

70. string(str)-method split(), n = 1,

71. value_counts() method

72. string(str)-method contains()